name: clean_arch_templeate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3
  shared_preferences: ^2.0.13
  # animation
  simple_animations: ^4.0.0
  supercharged: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/image/
    - assets/images/svg/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
